// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Server side message decoration
type ExamplePrototubeMessage struct {
	// int32 field
	Int32Field int32 `protobuf:"varint,1,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	// int64 field
	Int64Field int64 `protobuf:"varint,2,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	// double field
	DoubleField float64 `protobuf:"fixed64,3,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	// string field
	StringField string `protobuf:"bytes,4,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	// bytes field
	BytesField           []byte   `protobuf:"bytes,5,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExamplePrototubeMessage) Reset()         { *m = ExamplePrototubeMessage{} }
func (m *ExamplePrototubeMessage) String() string { return proto.CompactTextString(m) }
func (*ExamplePrototubeMessage) ProtoMessage()    {}
func (*ExamplePrototubeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *ExamplePrototubeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExamplePrototubeMessage.Unmarshal(m, b)
}
func (m *ExamplePrototubeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExamplePrototubeMessage.Marshal(b, m, deterministic)
}
func (m *ExamplePrototubeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExamplePrototubeMessage.Merge(m, src)
}
func (m *ExamplePrototubeMessage) XXX_Size() int {
	return xxx_messageInfo_ExamplePrototubeMessage.Size(m)
}
func (m *ExamplePrototubeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ExamplePrototubeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ExamplePrototubeMessage proto.InternalMessageInfo

func (m *ExamplePrototubeMessage) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *ExamplePrototubeMessage) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *ExamplePrototubeMessage) GetDoubleField() float64 {
	if m != nil {
		return m.DoubleField
	}
	return 0
}

func (m *ExamplePrototubeMessage) GetStringField() string {
	if m != nil {
		return m.StringField
	}
	return ""
}

func (m *ExamplePrototubeMessage) GetBytesField() []byte {
	if m != nil {
		return m.BytesField
	}
	return nil
}

func init() {
	proto.RegisterType((*ExamplePrototubeMessage)(nil), "ExamplePrototubeMessage")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0x31, 0x6a, 0xc3, 0x30,
	0x14, 0xc6, 0x71, 0x5e, 0x5d, 0x17, 0x2a, 0xbb, 0x4b, 0x29, 0x6d, 0xb7, 0xaa, 0x9d, 0x34, 0x69,
	0xa8, 0x8d, 0x0f, 0x50, 0x68, 0xb6, 0x40, 0xd0, 0x05, 0x82, 0x14, 0xbd, 0x38, 0x02, 0xc5, 0x32,
	0x96, 0x0c, 0xc9, 0xf5, 0x72, 0xb2, 0x60, 0x49, 0x78, 0xfd, 0xf3, 0x83, 0x8f, 0x8f, 0xbc, 0xe0,
	0x45, 0x9e, 0x47, 0x8b, 0x7c, 0x9c, 0x5c, 0x70, 0x3f, 0x37, 0x20, 0x1f, 0xff, 0xa9, 0xec, 0x96,
	0x10, 0x66, 0x85, 0x5b, 0xf4, 0x5e, 0xf6, 0xf8, 0xfa, 0x45, 0x2a, 0x33, 0x84, 0xe6, 0x77, 0x7f,
	0x34, 0x68, 0xf5, 0x27, 0x50, 0x60, 0xa5, 0x20, 0x31, 0x6d, 0x96, 0x92, 0x41, 0xd7, 0x66, 0xf0,
	0x40, 0x81, 0x15, 0x11, 0x74, 0x6d, 0x02, 0xdf, 0xa4, 0xd6, 0x6e, 0x56, 0x16, 0xb3, 0x28, 0x28,
	0x30, 0x10, 0x55, 0x6a, 0x2b, 0xf1, 0x61, 0x32, 0x43, 0x9f, 0xc9, 0x23, 0x05, 0xf6, 0x2c, 0xaa,
	0xd4, 0xd6, 0x19, 0x75, 0x0d, 0xe8, 0xb3, 0x28, 0x29, 0xb0, 0x5a, 0x90, 0x98, 0x22, 0xf8, 0x7b,
	0x27, 0x6f, 0xc6, 0x71, 0x69, 0xc3, 0xe1, 0x24, 0xcd, 0xc0, 0xb5, 0x0c, 0x92, 0x1b, 0x6d, 0xd5,
	0x53, 0xfc, 0xd8, 0xdc, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x19, 0x47, 0x5a, 0xf4, 0x00, 0x00,
	0x00,
}
